DROP DATABASE IF EXISTS streamstats;
CREATE DATABASE streamstats;
USE streamstats;

CREATE TABLE users
(
	USERID 			INT(10) UNSIGNED 	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TWITCHUSERID 	VARCHAR(255) 		NOT NULL UNIQUE KEY,
	email 			VARCHAR(255) 		NOT NULL,
	username 		VARCHAR(255) 		NOT NULL
);

CREATE TABLE games
(
	GAMEID 			INT(10) UNSIGNED 	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TWITCHGAMEID 	VARCHAR(255) 		NOT NULL UNIQUE KEY,
	game_name 		VARCHAR(255) 		NOT NULL,
	last_seen       DATETIME			NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE streams
(
	STREAMID 		INT(10) UNSIGNED 	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	stream_title 	VARCHAR(255) 		NOT NULL DEFAULT '',
	GAMEID 			INT(10) UNSIGNED	NOT NULL,
	viewers 		INT(10) UNSIGNED 	NOT NULL DEFAULT 0,
	date_started 	DATETIME 			NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_streams_GAMEID
		FOREIGN KEY (GAMEID)
		REFERENCES games(GAMEID)
		ON DELETE CASCADE
);