version: '3.8'

services:
  app:
    image: php:8.1-fpm-buster
    container_name: stream_stats_php
    volumes:
      - ./:/home/app:rw
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: stream_stats_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/home/app:rw
      - ./dev-env/api-streamstats.conf:/etc/nginx/conf.d/api-streamstats.conf:ro
    networks:
      - app-network

  redis:
    container_name: stream_stats_redis
    image: redis:7.0.4
    restart: unless-stopped
    ports:
      - 6379
    networks:
      - app-network
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge