version: '3.8'

services:
  app:
    build: dev-env/php
    container_name: stream_stats_php
    restart: unless-stopped
    command: bash -c "php /home/app/dev-env/bootstrap_project.php"
    depends_on:
      - mysql
    environment:
      DB_HOST: stream_stats_mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: test_password
      REDIS_HOST: stream_stats_redis
      REDIS_PORT: 6379
    volumes:
      - ./:/home/app:rw
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: stream_stats_nginx
    restart: unless-stopped
    depends_on:
      - app
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/home/app:rw
      - ./dev-env/api-streamstats.conf:/etc/nginx/conf.d/api-streamstats.conf:ro
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: stream_stats_mysql
    restart: unless-stopped
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: streamstats
    volumes:
      - ./local/mysql:/var/lib/mysql
      - ./db-files/streamstats_schema.sql:/root/streamstats_schema.sql
    networks:
      - app-network

  redis:
    container_name: stream_stats_redis
    image: redis:7.0.4
    restart: unless-stopped
    ports:
      - 6379
    networks:
      - app-network
    volumes:
      - ./local/redis:/data

networks:
  app-network:
    driver: bridge